version: "2.1"

services:

  webtop:
    image: ghcr.io/linuxserver/webtop:latest
    container_name: webtop
    privileged: true #optional
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 8200:3000
    shm_size: "1gb" #optional
    restart: unless-stopped
    
    
